language: smalltalk

sudo: required

os:
  - linux

smalltalk:
  - Pharo-7.0
  - Pharo-6.0
  - Pharo-5.0

env:
  - MONGODB=4.0
  - MONGODB=3.6
  - MONGODB=3.4

matrix:
  # Finish the build as soon as one job fails
  fast_finish: true

before_install:
- bash .install_mongodb_on_travis.sh
- sleep 15  # https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections
- mongo --eval 'db.version();'

before_script:
  - "mongo test --eval 'db.createUser({ \"user\": \"pharounittest\", \"pwd\": \"test\", roles: [] });'"

# bob-bench xUnit file analysis
after_script:
  - pip install --user benchupload && benchupload
